# Generated by Django 3.1 on 2020-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog', '0002_auto_20200826_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='post_img'),
        ),
    ]
