# Generated by Django 3.1 on 2020-08-08 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.IntegerField(blank=True, default=0, null=True)),
                ('savings', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('adharcard_number', models.IntegerField(blank=True, default='', null=True)),
                ('profile_image', models.ImageField(default='None', upload_to='profile_image')),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('mobile_number', models.IntegerField(blank=True, default='', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
